// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type AccountInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthPayload struct {
	Token string   `json:"token"`
	User  *Account `json:"user"`
}

type Mutation struct {
}

type PaginationInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Post struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Author    *Account  `json:"author"`
	CreatedAt time.Time `json:"createdAt"`
}

type PostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}

type SearchInput struct {
	Query      string           `json:"query"`
	Pagination *PaginationInput `json:"pagination,omitempty"`
}

type SearchResult struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Snippet   string    `json:"snippet"`
	CreatedAt time.Time `json:"createdAt"`
}
